name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t typingstats-frontend .

      - name: Stop old container
        run: |
          docker stop typingstats-frontend || true
          docker rm typingstats-frontend || true

      - name: Run new container
        run: |
          docker run -d \
            --name typingstats-frontend \
            -p 3000:80 \
            --restart unless-stopped \
            typingstats-frontend
      
      - name: Notify Discord
        if: always()
        run: |
          STATUS="${{ job.status }}"
          COMMITS=$(git log -3 --pretty=format:"- %s (%an)")

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"content\": \" **Deploy $STATUS**\n\n ${{ github.repository }}\n https://github.com/${{ github.repository }}/commit/${{ github.sha }}\n\n Commits:\n$COMMITS\"
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}